rockwell: &rockwell
  name: rockwell
  enabled: !!bool true
  scan_interval: !!int 1500
  connector: EthernetIP
  rbe: !!bool true
  type: !!int 5
  address: 192.168.111.20
  path: 1,0
  log: !!int 0
  timeout: !!int 1000
  bypass_ping: !!bool false
  init_script: ~
  enter_script: ~
  exit_script: ~
  deinit_script: ~
  strip_path_prefix: !!bool false
  items:
    - name: Execution
      enabled: !!bool true
      type: bool
      address: B3:0/3
      script: |
        local m = { [0]='Ready', [1]='Active' };
        return m[result and 1 or 0];
    - name: GoodPartCount
      enabled: !!bool true
      type: int
      address: N7:1
