sources:
  - name: plc1
    enabled: !!bool false
    connector: EthernetIP
    type: !!int 5
    address: 192.168.111.20
    log: !!int 3
    timeout: !!int 1000
    items:
      - name: boolTag1
        type: bool
        address: B3:0/2
      - name: boolTag2
        type: bool
        address: B3:0/3
  - name: mqtt1
    enabled: !!bool true
    connector: MQTT
    address: wss.sharc.tech
    port: !!int 1883
    items:
      - name: subscribe1
        address: sharc/+/evt/#