eipSource1: &eipSource1
  name: eipSource1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: EthernetIP
  rbe: !!bool true
  type: !!int 5
  address: 192.168.111.20
  path: 1,0
  log: !!int 0
  timeout: !!int 1000
  items:
    - name: boolTag1
      enabled: !!bool true
      type: bool
      address: B3:0/2
    - name: boolTag2
      enabled: !!bool true
      type: bool
      address: B3:0/3
