modbusSource1: &modbusSource1
  name: modbusSource1
  enabled: !!bool false
  scan_interval: !!int 1000
  connector: ModbusTCP
  rbe: !!bool true
  address: 192.168.111.20
  port: !!int 502
  slave: !!int 1
  timeout: !!int 1000
  init_script: |
    -- https://github.com/iryont/lua-struct
    struct = require('struct')
  items:
    - name: DigitalOutputsRead
      enabled: !!bool true
      type: !!int 1
      address: !!int 16
      count: !!int 12
      script: |
        set('outputs', result);
        return nil;
    - name: DO0
      enabled: !!bool true
      script: |
        return get('outputs', nil)[0];
    
