mtconnectSink1: &mtconnectSink1
  name: mtconnectSink1
  enabled: !!bool false
  scan_interval: !!int 1000
  connector: MTConnectAgent
  port: !!int 5000
  device_uuid: 123
  device_id: device1
  device_name: device1
  device_manufacturer: acme
  device_model: 123
  device_serial_number: 123
