msSqlSource1: &msSqlSource1
  name: msSqlSource1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: MSSQL
  rbe: !!bool true
  connection_string: Server=172.16.10.5;Database=Tykma;User Id=datareader;Password=datareader;
  command_text: select top * from dbo.SiliconeRubberOrders;
  init_script: ~
  deinit_script: ~
  enter_script: ~
  exit_script: ~
  items:
    - name: OrderNumber
      enabled: !!bool true
      address: ManufacturingOrderNumber
      script: return result[0];
    - name: OrderQuantity
      enabled: !!bool true
      address: OrderQuantity
      script: return result[0];
