instanceMotor1A: &instanceMotor1A
  name: ChicagoPlant
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: MQTT
  rbe: !!bool true
  itemized_read: !!bool true
  address: wss.sharc.tech
  port: !!int 1883
  qos: !!int 0
  init_script: |
    -- https://github.com/rxi/json.lua
    json = require('json');
  deinit_script: ~
  enter_script: ~
  exit_script: ~
  items:
    - name: Amperage
      address: sharc/08d1f9540058/evt/io/s3
      script: |
        set(this.Name, json.decode(result).v.s3.v);
        return nil;
    - name: Rpm
      address: sharc/08d1f953ffe4/evt/io/s1
      script: |
        set(this.Name, json.decode(result).v.s1.v);
        return nil;
    - name: Temperature
      address: sharc/48e7290b118c/evt/io/temperature
      script: |
        set(this.Name, json.decode(result).v.v);
        return nil;
    - name: Vibration
      address: sharc/48e7290b118c/evt/io/Xhz
      script: |
        set(this.Name, json.decode(result).v.v);
        return nil;
    - name: BeltSpeed
      address: sharc/08d1f9540b8c/evt/io/s3
      script: |
        set(this.Name, json.decode(result).v.s3.v);
        return nil;
    - name: WC01/Motor
      address: ~
      script: |
        local motor = {
          name = "WC01-Motor",
          amperage = cache("Amperage", 0),
          rpm = cache("Rpm", 0),
          temperature = cache("Temperature", 0),
          vibration = cache("Vibration", 0),
          belt_speed = cache("BeltSpeed", 0)
        }
        --print(json.encode(motor));
        return motor;
    - name: Humidity
      address: sharc/08d1f953fffc/evt/io/humidity
      script: |
        return json.decode(result).v.v;
