smartPacSource1: &smartPacSource1
  name: smartPacSource1
  enabled: !!bool false
  scan_interval: !!int 1000
  connector: SmartPAC
  address: 172.16.200.18
  port: !!int 1007
  items:
    - name: PressType
      enabled: !!bool true
      script: |
        local m = { ['09010']='Straight Side', ['09011']='Gap Frame' };
        return (m[result[0]])
    - name: PressName
      enabled: !!bool true
      script: return result[1];
    - name: IsRunning
      enabled: !!bool true
      script: return tonumber(result[2]) == 1;
    - name: ToolNumber
      enabled: !!bool true
      script: return result[3];
    - name: ToolName
      enabled: !!bool true
      script: return result[4];
    - name: JobName
      enabled: !!bool true
      script: return result[5];
    - name: ShaftAngleOrSpeed
      enabled: !!bool true
      script: return tonumber(result[6]);
    - name: Error
      enabled: !!bool true
      script: return result[7];
    - name: DieProtectionSensorsEnabled
      enabled: !!bool true
      script: return tonumber(result[8]) == 1;
    - name: PartCount
      enabled: !!bool true
      script: return tonumber(result[9]);
    - name: PartPreset
      enabled: !!bool true
      script: return tonumber(result[10]);
    - name: LastJobChangeTime
      enabled: !!bool true
      script: return result[11];
    - name: CurrentTime
      enabled: !!bool true
      script: return result[12];
    - name: TonnageChannels
      enabled: !!bool true
      script: return tonumber(result[13]);
    - name: TonnageMonitorCapacity
      enabled: !!bool true
      script: return tonumber(result[14]);
    - name: Input1Tonnage
      enabled: !!bool true
      script: return tonumber(result[15]);
    - name: Input2Tonnage
      enabled: !!bool true
      script: return tonumber(result[16]);
    - name: Input3Tonnage
      enabled: !!bool true
      script: return tonumber(result[17]);
    - name: Input4Tonnage
      enabled: !!bool true
      script: return tonumber(result[18]);
    - name: PartNumber
      enabled: !!bool true
      script: return result[19];
    - name: OperatingMode
      enabled: !!bool true
      script: return tonumber(result[20]);
    - name: BrakeWarning
      enabled: !!bool true
      script: return tonumber(result[22]) == 1;
    - name: RtsFirmware
      enabled: !!bool true
      script: return result[25];
    - name: SerialNumber
      enabled: !!bool true
      script: return result[26];
    - name: LastPowerOnTime
      enabled: !!bool true
      script: return result[44];
    - name: JobPartsRemaining
      enabled: !!bool true
      script: return cache('./PartPreset') - cache('./PartCount');
    - name: JobPercentComplete
      enabled: !!bool true
      script: return cache('./PartCount') / cache('./PartPreset');
    - name: JobRunningHours
      enabled: !!bool true
      script: |
        local year, month, day, hour, min, sec = cache('./LastJobChangeTime'):match("(%d+)-(%d+)-(%d+) (%d+):(%d+):(%d+)");
        local lastJobChangeTimeMs = os.time({year=year, month=month, day=day, hour=hour, min=min, sec=sec})
        local runningDurationMs = os.time() - lastJobChangeTimeMs;
        local runningDurationHours = (os.time() - timestamp)/60/60;
