console: &console
  name: consoleSink1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: Console
  use_sink_transform: !!bool true
  exclude_filter:
    - mqttin/$SYSTEM
    - mqttin/loadtester
