httpServerSink1: &httpServerSink1
  name: httpServerSink1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: HTTPServer
  uri: http://localhost:8080/
  #uri: http://*:8080/
  use_sink_transform: !!bool false
  exclude_filter:
    - sharc1/$SYSTEM
