websocketServerSink1: &websocketServerSink1
  name: websocketServerSink1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: WebsocketServer
  uri: ws://127.0.0.1:8082/
  #use_sink_transform: !!bool true
