eipSource1: &eipSource1
  name: eipSource1
  enabled: !!bool false
  scan_interval: !!int 1000
  connector: EthernetIP
  rbe: !!bool true
  type: !!int 5
  address: 192.168.111.20
  path: 1,0
  log: !!int 0
  timeout: !!int 1000
  init_script: ~
  items:
    - name: boolSetUserCacheOnly
      enabled: !!bool true
      type: bool
      address: B3:0/2
      script: |
        set('boolTag', result);
        return nil;
    - name: boolGetUserCache
      enabled: !!bool true
      script: |
        return get('boolTag', false);
    - name: Execution
      enabled: !!bool true
      type: bool
      address: B3:0/3
      script: |
        local m = { [0]='Ready', [1]='Active' };
        return m[result and 1 or 0];
      meta:
        mtconnect: Device[name=device1]/Controller/Path/Execution[category=Event]
