haasSource1: &haasSource1
  name: haasSource1
  enabled: !!bool false
  scan_interval: !!int 1000
  connector: HaasSHDR
  rbe: !!bool true
  itemized_read: !!bool true
  address: 192.168.111.221
  port: !!int 9998
  timeout: !!int 1000
  heartbeat_interval: !!int 0
  retry_interval: !!int 10000
  init_script: |
    luanet.load_assembly("System")
    CLR = {
      env = luanet.import_type("System.Environment")
    };
  items:
    - name: scriptTag1
      enabled: !!bool true
      address: CPU
      script: |
        local cpu = tonumber(result);
        if cpu > 0.5 then
          return 'HIGH'
        else
          return 'LOW'
        end
