sinks:
  - *httpServerSink1
  - *influxLpSink1
  - *mqttSink1
  - *mtConnectSink1
  - *redisSink1
  - *shdrSink1
  - *sparkplugBSink1
  - *trakhoundHttpSink1
sources:
  - *ascCpcSource1
  - *eipSource1
  - *haasSource1
  - *httpServerSource1
  - *mettlerToledoScale1
  - *modbusSource1
  - *mqttSource1
  - *mtConnectSource1
  - *redisSource1
  - *scriptSource1
  - *smartPacSource1
  - *snmpSource1
  - *timebaseWsSource1
