sinks:
  - *httpServerSink1
  - *mqttSink1
  - *mtConnectSink1
  - *redisSink1
  - *shdrSink1
  - *sparkplugBSink1
sources:
  - *ascCpcSource1
  - *eipSource1
  - *haasSource1
  - *httpServerSource1
  - *mettlerToledoScale1
  - *modbusSource1
  - *mqttSource1
  - *mtConnectSource1
  - *scriptSource1
  - *snmpSource1
