mettlerToledoScale1: &mettlerToledoScale1
  # start reading: curl -d "{\"hello\":true}" http://localhost:8081/post/data
  # stop reading: curl -d "{\"hello\":false}" http://localhost:8081/post/data
  name: mettlerToledoScale1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: Script
  rbe: !!bool true
  init_script: |
    ip = '10.30.83.75';
    port = 1701;
    read_trigger = false;
  deinit_script: ~
  enter_script: |
    if not read_trigger then return end;
    read_trigger = false;
    local sock = socket.connect(ip, port);
    sock:settimeout(1, 'b');
    sock:send('user admin\r\n');
    sock.receive('*l');
    sock.send('pass admin\r\n');
    sock.receive('*l');
    sock.send('read wt0101\r\n');
    local response = sock.receive('*l');
    sock:close();
    local status, sequence, value = response:match("(%d%d)R(%d%d%d)~%s*(.+)");
    weight, units = value:match("([%d%.]+)~(.+)~");
  exit_script: ~
  items:
    - name: ReadTrigger
      enabled: !!bool true
      rbe: !!bool true
      script: |
        read_trigger = cache('httpServerSource1/postData', false);
        return nil;
    - name: Weight
      enabled: !!bool true
      rbe: !!bool true
      script: |
        return weight;
    - name: Units
      enabled: !!bool true
      rbe: !!bool true
      script: |
        return units;
