mqttSink1: &mqttSink1
  name: mqttSink1
  enabled: !!bool false
  scan_interval: !!int 1000
  connector: MQTT
  address: wss.sharc.tech
  port: !!int 1883
  base_topic: dime
  qos: !!int 0
  retain: !!bool true
