snmpSource1: &snmpSource1
  name: snmpSource1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: SNMP
  rbe: !!bool true
  address: 192.168.150.143
  port: !!int 161
  community: public
  timeout: !!int 1000
  init_script: ~
  items:
    - name: Temperature
      enabled: !!bool true
      address: 1.3.6.1.4.1.6574.1.2.0
    - name: Model
      enabled: !!bool true
      address: 1.3.6.1.4.1.6574.1.5.1.0
    - name: SerialNumber
      enabled: !!bool true
      address: 1.3.6.1.4.1.6574.1.5.2.0
