sparkplugBSink1: &sparkplugBSink1
  name: sparkplugBSink1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: SparkplugB
  address: localhost
  port: !!int 1883
  username: admin
  password: admin
  host_id: dime
  group_id: dime
  node_id: dime
  device_id: dime
  reconnect_interval: !!int 30000
