trakhoundHttpSink1: &trakhoundHttpSink1
  name: trakhoundHttpSink1
  enabled: !!bool false
  scan_interval: !!int 1000
  connector: TrakHoundHTTP
  address: localhost
  port: 8472
  use_ssl: false
  router: default
  base_path: Ladder99:/DIME/HttpSink
