// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Connectors/SplunkEhSdk/edgehub.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DIME.Connectors.SplunkEhSdk {
  /// <summary>
  /// Hub Version: 1.8 release
  /// </summary>
  public static partial class EdgeHubService
  {
    static readonly string __ServiceName = "edgehub.sdk.EdgeHubService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DIME.Connectors.SplunkEhSdk.GetDiscoveryResponse> __Marshaller_edgehub_sdk_GetDiscoveryResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DIME.Connectors.SplunkEhSdk.GetDiscoveryResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DIME.Connectors.SplunkEhSdk.GetReadingRequest> __Marshaller_edgehub_sdk_GetReadingRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DIME.Connectors.SplunkEhSdk.GetReadingRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DIME.Connectors.SplunkEhSdk.GetReadingResponse> __Marshaller_edgehub_sdk_GetReadingResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DIME.Connectors.SplunkEhSdk.GetReadingResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest> __Marshaller_edgehub_sdk_SendEventDataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse> __Marshaller_edgehub_sdk_SendEventDataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest> __Marshaller_edgehub_sdk_SendMetricDataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse> __Marshaller_edgehub_sdk_SendMetricDataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::DIME.Connectors.SplunkEhSdk.GetDiscoveryResponse> __Method_GetDiscovery = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::DIME.Connectors.SplunkEhSdk.GetDiscoveryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDiscovery",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_edgehub_sdk_GetDiscoveryResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DIME.Connectors.SplunkEhSdk.GetReadingRequest, global::DIME.Connectors.SplunkEhSdk.GetReadingResponse> __Method_GetReading = new grpc::Method<global::DIME.Connectors.SplunkEhSdk.GetReadingRequest, global::DIME.Connectors.SplunkEhSdk.GetReadingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetReading",
        __Marshaller_edgehub_sdk_GetReadingRequest,
        __Marshaller_edgehub_sdk_GetReadingResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DIME.Connectors.SplunkEhSdk.GetReadingRequest, global::DIME.Connectors.SplunkEhSdk.GetReadingResponse> __Method_GetReadingStreamResponse = new grpc::Method<global::DIME.Connectors.SplunkEhSdk.GetReadingRequest, global::DIME.Connectors.SplunkEhSdk.GetReadingResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetReadingStreamResponse",
        __Marshaller_edgehub_sdk_GetReadingRequest,
        __Marshaller_edgehub_sdk_GetReadingResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest, global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse> __Method_SendEventData = new grpc::Method<global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest, global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendEventData",
        __Marshaller_edgehub_sdk_SendEventDataRequest,
        __Marshaller_edgehub_sdk_SendEventDataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest, global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse> __Method_SendEventDataStream = new grpc::Method<global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest, global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SendEventDataStream",
        __Marshaller_edgehub_sdk_SendEventDataRequest,
        __Marshaller_edgehub_sdk_SendEventDataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest, global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse> __Method_SendMetricData = new grpc::Method<global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest, global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendMetricData",
        __Marshaller_edgehub_sdk_SendMetricDataRequest,
        __Marshaller_edgehub_sdk_SendMetricDataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest, global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse> __Method_SendMetricDataStream = new grpc::Method<global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest, global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SendMetricDataStream",
        __Marshaller_edgehub_sdk_SendMetricDataRequest,
        __Marshaller_edgehub_sdk_SendMetricDataResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DIME.Connectors.SplunkEhSdk.EdgehubReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for EdgeHubService</summary>
    public partial class EdgeHubServiceClient : grpc::ClientBase<EdgeHubServiceClient>
    {
      /// <summary>Creates a new client for EdgeHubService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public EdgeHubServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EdgeHubService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public EdgeHubServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected EdgeHubServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected EdgeHubServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DIME.Connectors.SplunkEhSdk.GetDiscoveryResponse GetDiscovery(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDiscovery(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DIME.Connectors.SplunkEhSdk.GetDiscoveryResponse GetDiscovery(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDiscovery, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DIME.Connectors.SplunkEhSdk.GetDiscoveryResponse> GetDiscoveryAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDiscoveryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DIME.Connectors.SplunkEhSdk.GetDiscoveryResponse> GetDiscoveryAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDiscovery, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DIME.Connectors.SplunkEhSdk.GetReadingResponse GetReading(global::DIME.Connectors.SplunkEhSdk.GetReadingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetReading(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DIME.Connectors.SplunkEhSdk.GetReadingResponse GetReading(global::DIME.Connectors.SplunkEhSdk.GetReadingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetReading, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DIME.Connectors.SplunkEhSdk.GetReadingResponse> GetReadingAsync(global::DIME.Connectors.SplunkEhSdk.GetReadingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetReadingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DIME.Connectors.SplunkEhSdk.GetReadingResponse> GetReadingAsync(global::DIME.Connectors.SplunkEhSdk.GetReadingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetReading, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::DIME.Connectors.SplunkEhSdk.GetReadingResponse> GetReadingStreamResponse(global::DIME.Connectors.SplunkEhSdk.GetReadingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetReadingStreamResponse(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::DIME.Connectors.SplunkEhSdk.GetReadingResponse> GetReadingStreamResponse(global::DIME.Connectors.SplunkEhSdk.GetReadingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetReadingStreamResponse, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse SendEventData(global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendEventData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse SendEventData(global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendEventData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse> SendEventDataAsync(global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendEventDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse> SendEventDataAsync(global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendEventData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest, global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse> SendEventDataStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendEventDataStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::DIME.Connectors.SplunkEhSdk.SendEventDataRequest, global::DIME.Connectors.SplunkEhSdk.SendEventDataResponse> SendEventDataStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SendEventDataStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse SendMetricData(global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendMetricData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse SendMetricData(global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendMetricData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse> SendMetricDataAsync(global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendMetricDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse> SendMetricDataAsync(global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendMetricData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest, global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse> SendMetricDataStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendMetricDataStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::DIME.Connectors.SplunkEhSdk.SendMetricDataRequest, global::DIME.Connectors.SplunkEhSdk.SendMetricDataResponse> SendMetricDataStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SendMetricDataStream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override EdgeHubServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EdgeHubServiceClient(configuration);
      }
    }

  }
}
#endregion
