rockwell: &rockwell
  name: rockwell
  enabled: !!bool true
  scan_interval: !!int 1500
  connector: EthernetIP
  type: !!int 5
  address: 192.168.111.20
  path: 1,0
  sink:
    transform:
      type: script
      template: Message.Data;
  items:
    - name: Execution
      type: bool
      address: B3:0/3
      script: |
        local states = { [0]='Idle', [1]='Running' };
        return states[result and 1 or 0];
    - name: GoodPartCount
      type: int
      address: N7:1
