sinks:
  - name: mqttSink1
    enabled: !!bool true
    scan_interval: !!int 1000
    connector: MQTT
    address: wss.sharc.tech
    port: !!int 1883
    base_topic: ids
  - name: shdrSink1
    enabled: !!bool true
    scan_interval: !!int 1000
    connector: MTConnect
    port: !!int 7878
    device_key: ~
    heartbeat_ms: !!int 10000
    filter_duplicates: !!bool true
sources:
  - name: plcSource1
    enabled: !!bool true
    scan_interval: !!int 1000
    connector: EthernetIP
    rbe: !!bool true
    type: !!int 5
    address: 192.168.111.20
    path: 1,0
    log: !!int 0
    timeout: !!int 1000
    items:
      - name: boolTag1
        enabled: !!bool true
        type: bool
        address: B3:0/2
      - name: boolTag2
        enabled: !!bool true
        type: bool
        address: B3:0/3
  - name: mqttSource1
    enabled: !!bool false
    scan_interval: !!int 1000
    rbe: !!bool true
    connector: MQTT
    address: wss.sharc.tech
    port: !!int 1883
    items:
      - name: subscribe1
        enabled: !!bool true
        address: sharc/+/evt/#