app:
  ring_buffer: !!int 4096
  http_server_uri: http://*:9999/
  ws_server_uri: ws://0.0.0.0:9998/
sinks:
  - *consoleSink1
  - *httpServerSink1
  - *splunkEhSdkSink1
sources:
  - *eipSource1
  - *haasSource1
  - *scriptSource1
