mtConnectSource1: &mtConnectSource1
  name: mtConnectSource1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: MTConnectAgent
  rbe: !!bool true
  itemized_read: !!bool true
  address: mtconnect.mazakcorp.com
  port: !!int 5719
  init_script: ~
  strip_path_prefix: !!bool true
  sink:
    transform:
      type: script
      template: >-
        Message.Data[0].Value + " TEST TEST"
  items:
    - name: Availability
      address: avail
      sink:
        mtconnect: Device[Name=device1]/Availability[Category=Event]
    - name: Execution
      address: execution
      sink:
        mtconnect: Device[Name=device1]/Controller/Path/Execution[Category=Event]
    - name: XLoad
      address: Xload
      sink:
        mtconnect: Device[Name=device1]/Axes/Linear[Name=X]/Load[Category=Sample]
