instanceMotor1B: &instanceMotor1B
  name: DetroitPlant
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: Script
  rbe: !!bool true
  init_script: |
    -- https://github.com/rxi/json.lua
    json = require('json');
  deinit_script: ~
  enter_script: ~
  exit_script: ~
  items:
    - name: WC02/Motor
      script: |
        local motor = {
          name = "WC02-Motor",
          available = cache("ChicagoPlant/$SYSTEM/IsConnected", false),
          amperage = cache("ChicagoPlant/Amperage", 0),
          rpm = cache("ChicagoPlant/Rpm", 0),
          temperature = cache("ChicagoPlant/Temperature", 0),
          vibration = cache("ChicagoPlant/Vibration", 0),
          belt_speed = cache("ChicagoPlant/BeltSpeed", 0),
        }
        --print(json.encode(motor));
        return motor;
    - name: Humidity
      script: |
        return cache("ChicagoPlant/Humidity", 0);
