app:
  ring_buffer: !!int 4096
  http_server_uri: http://127.0.0.1:9999/
  ws_server_uri: ws://127.0.0.1:9998/
sinks:
  - *consoleSink1
  - *httpServerSink1
  - *mqttSink1
  - *redisSink1
sources:
  - *instanceMotor1A
  - *instanceMotor1B
