redisSink1: &redisSink1
  name: redisSink1
  enabled: !!bool true
  scan_interval: !!int 1000
  connector: Redis
  address: 172.24.56.104:6379
  database: !!int 0
  include_filter:
    - DetroitPlant
